name: app_2
description: A new Flutter project.


environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/ci.jpg
  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf  

  - family: Source Sans Pro
    fonts: 
    - asset: fonts/SourceSansPro-Regular.ttf  

  - family: RubikDirt
    fonts: 
    - asset: fonts/RubikDirt-Regular.ttf  

